const brasil = {
  ro: [
    'Porto Velho',
    'Ji-Paraná',
    'Ariquemes',
    'Vilhena',
    'Cacoal',
    'Rolim de Moura',
    'Jaru',
    'Guajará-Mirim',
    'Ouro Preto do Oeste',
    'Pimenta Bueno',
    'Machadinho do Oeste',
    "Espigão d'Oeste",
    'Buritis',
    'Nova Mamoré',
    'Candeias do Jamari',
    'São Miguel do Guaporé',
    'Alta Floresta do Oeste',
    'Presidente Médici',
    'Alto Paraíso',
    'São Francisco do Guaporé',
    'Cerejeiras',
    'Nova Brasilândia do Oeste',
    'Colorado do Oeste',
    'Cujubim',
    'Alvorada do Oeste',
    'Costa Marques',
    'Monte Negro',
    'Alto Alegre dos Parecis',
    'Seringueiras',
    'Urupá',
    'Chupinguaia',
    'Mirante da Serra',
    'Campo Novo de Rondônia',
    'Itapuã do Oeste',
    'Theobroma',
    'Governador Jorge Teixeira',
    'Vale do Anari',
    'Novo Horizonte do Oeste',
    'Corumbiara',
    'Santa Luzia do Oeste',
    'Vale do Paraíso',
    'Ministro Andreazza',
    'Nova União',
    'Cabixi',
    'São Felipe do Oeste',
    'Teixeirópolis',
    'Cacaulândia',
    'Parecis',
    'Rio Crespo',
    'Castanheiras',
    'Primavera de Rondônia',
    'Pimenteiras do Oeste',
  ],
  mt: [
    'Cuiabá',
    'Várzea Grande',
    'Rondonópolis',
    'Sinop',
    'Sorriso',
    'Tangará da Serra',
    'Cáceres',
    'Primavera do Leste',
    'Lucas do Rio Verde',
    'Barra do Garças',
    'Alta Floresta',
    'Nova Mutum',
    'Pontes e Lacerda',
    'Campo Novo do Parecis',
    'Juína',
    'Campo Verde',
    'Confresa',
    'Juara',
    'Peixoto de Azevedo',
    'Colíder',
    'Poconé',
    'Guarantã do Norte',
    'Barra do Bugres',
    'Água Boa',
    'Sapezal',
    'Jaciara',
    "Mirassol d'Oeste",
    'Querência',
    'Paranatinga',
    'Canarana',
    'Colniza',
    'Aripuanã',
    'Nova Xavantina',
    'Poxoréu',
    'Diamantino',
    'Matupá',
    'Vila Rica',
    'Chapada dos Guimarães',
    'Comodoro',
    'Pedra Preta',
    'São José dos Quatro Marcos',
    'Alto Araguaia',
    'Brasnorte',
    'Vila Bela da Santíssima Trindade',
    'Nova Olímpia',
    'Nobres',
    'Rosário Oeste',
    'Campinápolis',
    'Santo Antônio de Leverger',
    'São José do Rio Claro',
    'Araputanga',
    'Tapurah',
    'Porto Alegre do Norte',
    'Nova Bandeirantes',
    'São Félix do Araguaia',
    'Alto Garças',
    'Nossa Senhora do Livramento',
    'Vera',
    'Itiquira',
    'Nova Canaã do Norte',
    'Paranaíta',
    'Nova Ubiratã',
    'Juscimeira',
    'Marcelândia',
    'Carlinda',
    'Cotriguaçu',
    'Guiratinga',
    'Alto Taquari',
    'Terra Nova do Norte',
    'Arenápolis',
    'Feliz Natal',
    'Juruena',
    'Porto Esperidião',
    'Tabaporã',
    'Cláudia',
    'Campos de Júlio',
    'Gaúcha do Norte',
    'Apiacás',
    'Jauru',
    'Nova Monte Verde',
    'Alto Paraguai',
    'Dom Aquino',
    'Ipiranga do Norte',
    'Santa Terezinha',
    'Itanhangá',
    'Castanheira',
    'Jangada',
    'Bom Jesus do Araguaia',
    'Barão de Melgaço',
    'Denise',
    'Pontal do Araguaia',
    'Novo São Joaquim',
    'Nova Lacerda',
    'Novo Mundo',
    'Cocalinho',
    'General Carneiro',
    'São José do Xingu',
    'Nortelândia',
    'Nova Maringá',
    'Alto Boa Vista',
    'Porto dos Gaúchos',
    'Santa Carmem',
    'Itaúba',
    'Acorizal',
    'Curvelândia',
    "Lambari d'Oeste",
    'Nova Guarita',
    'Rio Branco',
    'Canabrava do Norte',
    'Nova Santa Helena',
    'Nova Nazaré',
    'São Pedro da Cipa',
    'Torixoréu',
    'Santo Antônio do Leste',
    'Nova Brasilândia',
    'União do Sul',
    'Araguaiana',
    "Conquista d'Oeste",
    'Salto do Céu',
    'Nova Marilândia',
    'Rondolândia',
    'Novo Horizonte do Norte',
    'Santa Rita do Trivelato',
    'Porto Estrela',
    "Figueirópolis d'Oeste",
    'Planalto da Serra',
    'Tesouro',
    "Glória d'Oeste",
    'Vale de São Domingos',
    'São José do Povo',
    'Santa Cruz do Xingu',
    'Ribeirãozinho',
    'Santo Afonso',
    'Luciara',
    'Indiavaí',
    'Reserva do Cabaçal',
    'Novo Santo Antônio',
    'Ponte Branca',
    'Serra Nova Dourada',
    'Araguainha',
  ],
  go: [
    'Goiânia',
    'Aparecida de Goiânia',
    'Anápolis',
    'Rio Verde',
    'Águas Lindas de Goiás',
    'Luziânia',
    'Valparaíso de Goiás',
    'Senador Canedo',
    'Trindade',
    'Formosa',
    'Catalão',
    'Itumbiara',
    'Planaltina',
    'Jataí',
    'Novo Gama',
    'Caldas Novas',
    'Cidade Ocidental',
    'Goianésia',
    'Santo Antônio do Descoberto',
    'Goianira',
    'Mineiros',
    'Cristalina',
    'Inhumas',
    'Morrinhos',
    'Quirinópolis',
    'Jaraguá',
    'Itaberaí',
    'Porangatu',
    'Uruaçu',
    'Santa Helena de Goiás',
    'Iporá',
    'Goiatuba',
    'Padre Bernardo',
    'Niquelândia',
    'Posse',
    'Bela Vista de Goiás',
    'São Luís de Montes Belos',
    'Pires do Rio',
    'Nerópolis',
    'Palmeiras de Goiás',
    'Hidrolândia',
    'Minaçu',
    'Alexânia',
    'Pirenópolis',
    'Itapuranga',
    'Ipameri',
    'Cocalzinho de Goiás',
    'Piracanjuba',
    'Goiás',
    'Bom Jesus de Goiás',
    'Silvânia',
    'Ceres',
    'São Miguel do Araguaia',
    'Acreúna',
    'Itapaci',
    'Rubiataba',
    'Jussara',
    'Guapó',
    'Abadia de Goiás',
    'Anicuns',
    'Aragarças',
    'Pontalina',
    'Campos Belos',
    'Abadiânia',
    'Crixás',
    'Indiara',
    'São Simão',
    'Caiapônia',
    'Orizona',
    'Vianópolis',
    'Mozarlândia',
    "São João d'Aliança",
    'Goianápolis',
    'Caçu',
    'Flores de Goiás',
    'Uruana',
    'Chapadão do Céu',
    'Nova Crixás',
    'Montividiu',
    'Campinorte',
    'Rialma',
    'Aragoiânia',
    'Edéia',
    'Piranhas',
    'Cachoeira Alta',
    'Mara Rosa',
    'Paraúna',
    'Santa Terezinha de Goiás',
    'Iaciara',
    'Buriti Alegre',
    'Barro Alto',
    'Alto Paraíso de Goiás',
    'Bonfinópolis',
    'Cavalcante',
    'Firminópolis',
    'Corumbá de Goiás',
    'São Domingos',
    'Maurilândia',
    'Montes Claros de Goiás',
    'Paranaiguara',
    'Carmo do Rio Verde',
    'Nazário',
    'Nova Veneza',
    'Petrolina de Goiás',
    'Leopoldo de Bulhões',
    'Vicentinópolis',
    'Corumbaíba',
    'Itauçu',
    'Alvorada do Norte',
    'Nova Glória',
    'Sanclerlândia',
    'Serranópolis',
    'Mambaí',
    'Aruanã',
    'Campo Limpo de Goiás',
    'Itapirapuã',
    'Terezópolis de Goiás',
    'Cezarina',
    'Bom Jardim de Goiás',
    'Cachoeira Dourada',
    'Santo Antônio de Goiás',
    'Campo Alegre de Goiás',
    'Cabeceiras',
    'Santa Rita do Araguaia',
    'Ouvidor',
    'Joviânia',
    'Faina',
    'Itarumã',
    'Araguapaz',
    'Doverlândia',
    'Monte Alegre de Goiás',
    'Jandaia',
    'Mundo Novo',
    'Santa Bárbara de Goiás',
    'Alto Horizonte',
    'Britânia',
    'Inaciolândia',
    'Fazenda Nova',
    'Simolândia',
    'Vila Propício',
    'Água Fria de Goiás',
    'Caturaí',
    'Gouvelândia',
    'Goiandira',
    'Santa Fé de Goiás',
    'São Luiz do Norte',
    'Itaguari',
    'Americano do Brasil',
    'Itaguaru',
    'Hidrolina',
    'Turvelândia',
    'Mossâmedes',
    'Formoso',
    'Itajá',
    'Turvânia',
    'Caldazinha',
    'Campos Verdes',
    'Divinópolis de Goiás',
    'Santo Antônio da Barra',
    'São Miguel do Passa-Quatro',
    'Porteirão',
    'Aporé',
    'Ouro Verde de Goiás',
    'Matrinchã',
    'Taquaral de Goiás',
    'Guarani de Goiás',
    'Brazabrantes',
    'Rianápolis',
    'Colinas do Sul',
    'Rio Quente',
    'Cromínia',
    'Edealina',
    'Uirapuru',
    'Araçu',
    'Palminópolis',
    'Amaralina',
    'Damianópolis',
    'Campestre de Goiás',
    'Varjão',
    'Campinaçu',
    'Novo Planalto',
    'Vila Boa',
    'Cristianópolis',
    'Montividiu do Norte',
    'Mutunópolis',
    'Santa Isabel',
    'Palestina de Goiás',
    'Gameleira de Goiás',
    'Aurilândia',
    'Baliza',
    'Professor Jamil',
    'Santa Tereza de Goiás',
    'Portelândia',
    'Estrela do Norte',
    'Perolândia',
    'Bonópolis',
    'Heitoraí',
    'Trombas',
    'Urutaí',
    'Buritinópolis',
    'Santa Cruz de Goiás',
    'Nova Roma',
    'Nova Iguaçu de Goiás',
    'Amorinópolis',
    'Castelândia',
    'Panamá',
    'Arenópolis',
    'Santa Rita do Novo Destino',
    "Sítio d'Abadia",
    'Jaupaci',
    'Aparecida do Rio Doce',
    'Cumari',
    'Ipiranga de Goiás',
    'Três Ranchos',
    'Santa Rosa de Goiás',
    'Damolândia',
    'Buriti de Goiás',
    'Teresina de Goiás',
    'Marzagão',
    'Ivolândia',
    'Mimoso de Goiás',
    'Israelândia',
    'Mairipotaba',
    'Avelinópolis',
    'Morro Agudo de Goiás',
    'Córrego do Ouro',
    'Adelândia',
    'Pilar de Goiás',
    'Palmelo',
    'Nova América',
    'Guaraíta',
    'Guarinos',
    'São Patrício',
    'Jesúpolis',
    'Nova Aurora',
    'Diorama',
    'São João da Paraúna',
    'Aloândia',
    'Água Limpa',
    'Davinópolis',
    'Moiporá',
    'Lagoa Santa',
    'Cachoeira de Goiás',
    'Anhanguera',
  ],
  mg: [
    'Abadia dos Dourados',
    'Abaeté',
    'Abre Campo',
    'Acaiaca',
    'Açucena',
    'Água Boa',
    'Água Comprida',
    'Aguanil',
    'Águas Formosas',
    'Águas Vermelhas',
    'Aimorés',
    'Aiuruoca',
    'Alagoa',
    'Albertina',
    'Além Paraíba',
    'Alfenas',
    'Alfredo Vasconcelos',
    'Almenara',
    'Alpercata',
    'Alpinópolis',
    'Alterosa',
    'Alto Caparaó',
    'Alto Jequitibá',
    'Alto Rio Doce',
    'Alvarenga',
    'Alvinópolis',
    'Alvorada de Minas',
    'Amparo da Serra',
    'Andradas',
    'Andrelândia',
    'Angelândia',
    'Antônio Carlos',
    'Antônio Dias',
    'Antônio Prado de Minas',
    'Araçaí',
    'Aracitaba',
    'Araçuaí',
    'Araguari',
    'Arantina',
    'Araponga',
    'Araporã',
    'Arapuá',
    'Araújos',
    'Araxá',
    'Arceburgo',
    'Arcos',
    'Areado',
    'Argirita',
    'Aricanduva',
    'Arinos',
    'Astolfo Dutra',
    'Ataléia',
    'Augusto de Lima',
    'Baependi',
    'Baldim',
    'Bambuí',
    'Bandeira',
    'Bandeira do Sul',
    'Barão de Cocais',
    'Barão de Monte Alto',
    'Barbacena',
    'Barra Longa',
    'Barroso',
    'Bela Vista de Minas',
    'Belmiro Braga',
    'Belo Horizonte',
    'Belo Oriente',
    'Belo Vale',
    'Berilo',
    'Berizal',
    'Bertópolis',
    'Betim',
    'Bias Fortes',
    'Bicas',
    'Biquinhas',
    'Boa Esperança',
    'Bocaina de Minas',
    'Bocaiuva',
    'Bom Despacho',
    'Bom Jardim de Minas',
    'Bom Jesus da Penha',
    'Bom Jesus do Amparo',
    'Bom Jesus do Galho',
    'Bom Repouso',
    'Bom Sucesso',
    'Bonfim',
    'Bonfinópolis de Minas',
    'Bonito de Minas',
    'Borda da Mata',
    'Botelhos',
    'Botumirim',
    'Brás Pires',
    'Brasilândia de Minas',
    'Brasília de Minas',
    'Braúnas',
    'Brazópolis',
    'Brumadinho',
    'Bueno Brandão',
    'Buenópolis',
    'Bugre',
    'Buritis',
    'Buritizeiro',
    'Cabeceira Grande',
    'Cabo Verde',
    'Cachoeira da Prata',
    'Cachoeira de Minas',
    'Cachoeira de Pajeú',
    'Cachoeira Dourada',
    'Caetanópolis',
    'Caeté',
    'Caiana',
    'Cajuri',
    'Caldas',
    'Camacho',
    'Camanducaia',
    'Cambuí',
    'Cambuquira',
    'Campanário',
    'Campanha',
    'Campestre',
    'Campina Verde',
    'Campo Azul',
    'Campo Belo',
    'Campo do Meio',
    'Campo Florido',
    'Campos Altos',
    'Campos Gerais',
    'Cana Verde',
    'Canaã',
    'Canápolis',
    'Candeias',
    'Cantagalo',
    'Caparaó',
    'Capela Nova',
    'Capelinha',
    'Capetinga',
    'Capim Branco',
    'Capinópolis',
    'Capitão Andrade',
    'Capitão Enéas',
    'Capitólio',
    'Caputira',
    'Caraí',
    'Caranaíba',
    'Carandaí',
    'Carangola',
    'Caratinga',
    'Carbonita',
    'Careaçu',
    'Carlos Chagas',
    'Carmésia',
    'Carmo da Cachoeira',
    'Carmo da Mata',
    'Carmo de Minas',
    'Carmo do Cajuru',
    'Carmo do Paranaíba',
    'Carmo do Rio Claro',
    'Carmópolis de Minas',
    'Carneirinho',
    'Carrancas',
    'Carvalhópolis',
    'Carvalhos',
    'Casa Grande',
    'Cascalho Rico',
    'Cássia',
    'Cataguases',
    'Catas Altas da Noruega',
    'Catas Altas',
    'Catuji',
    'Catuti',
    'Caxambu',
    'Cedro do Abaeté',
    'Central de Minas',
    'Centralina',
    'Chácara',
    'Chalé',
    'Chapada do Norte',
    'Chapada Gaúcha',
    'Chiador',
    'Cipotânea',
    'Claraval',
    'Claro dos Poções',
    'Cláudio',
    'Coimbra',
    'Coluna',
    'Comendador Gomes',
    'Comercinho',
    'Conceição da Aparecida',
    'Conceição da Barra de Minas',
    'Conceição das Alagoas',
    'Conceição das Pedras',
    'Conceição de Ipanema',
    'Conceição do Mato Dentro',
    'Conceição do Pará',
    'Conceição do Rio Verde',
    'Conceição dos Ouros',
    'Cônego Marinho',
    'Confins',
    'Congonhal',
    'Congonhas do Norte',
    'Congonhas',
    'Conquista',
    'Conselheiro Lafaiete',
    'Conselheiro Pena',
    'Consolação',
    'Contagem',
    'Coqueiral',
    'Coração de Jesus',
    'Cordisburgo',
    'Cordislândia',
    'Corinto',
    'Coroaci',
    'Coromandel',
    'Coronel Fabriciano',
    'Coronel Murta',
    'Coronel Pacheco',
    'Coronel Xavier Chaves',
    'Córrego Danta',
    'Córrego do Bom Jesus',
    'Córrego Fundo',
    'Córrego Novo',
    'Couto de Magalhães de Minas',
    'Crisólita',
    'Cristais',
    'Cristália',
    'Cristiano Otoni',
    'Cristina',
    'Crucilândia',
    'Cruzeiro da Fortaleza',
    'Cruzília',
    'Cuparaque',
    'Curral de Dentro',
    'Curvelo',
    'Datas',
    'Delfim Moreira',
    'Delfinópolis',
    'Delta',
    'Descoberto',
    'Desterro de Entre Rios',
    'Desterro do Melo',
    'Diamantina',
    'Diogo de Vasconcelos',
    'Dionísio',
    'Divinésia',
    'Divino',
    'Divino das Laranjeiras',
    'Divinolândia de Minas',
    'Divinópolis',
    'Divisa Alegre',
    'Divisa Nova',
    'Divisópolis',
    'Dom Bosco',
    'Dom Cavati',
    'Dom Joaquim',
    'Dom Silvério',
    'Dom Viçoso',
    'Dona Euzébia',
    'Dores de Campos',
    'Dores de Guanhães',
    'Dores do Indaiá',
    'Dores do Turvo',
    'Doresópolis',
    'Douradoquara',
    'Durandé',
    'Elói Mendes',
    'Engenheiro Caldas',
    'Engenheiro Navarro',
    'Entre Folhas',
    'Entre Rios de Minas',
    'Ervália',
    'Esmeraldas',
    'Espera Feliz',
    'Espinosa',
    'Espírito Santo do Dourado',
    'Estiva',
    'Estrela Dalva',
    'Estrela do Indaiá',
    'Estrela do Sul',
    'Eugenópolis',
    'Ewbank da Câmara',
    'Extrema',
    'Fama',
    'Faria Lemos',
    'Felício dos Santos',
    'Felisburgo',
    'Felixlândia',
    'Fernandes Tourinho',
    'Ferros',
    'Fervedouro',
    'Florestal',
    'Formiga',
    'Formoso',
    'Fortaleza de Minas',
    'Fortuna de Minas',
    'Francisco Badaró',
    'Francisco Dumont',
    'Francisco Sá',
    'Franciscópolis',
    'Frei Gaspar',
    'Frei Inocêncio',
    'Frei Lagonegro',
    'Fronteira',
    'Fronteira dos Vales',
    'Fruta de Leite',
    'Frutal',
    'Funilândia',
    'Galileia',
    'Gameleiras',
    'Glaucilândia',
    'Goiabeira',
    'Goianá',
    'Gonçalves',
    'Gonzaga',
    'Gouveia',
    'Governador Valadares',
    'Grão Mogol',
    'Grupiara',
    'Guanhães',
    'Guapé',
    'Guaraciaba',
    'Guaraciama',
    'Guaranésia',
    'Guarani',
    'Guarará',
    'Guarda-Mor',
    'Guaxupé',
    'Guidoval',
    'Guimarânia',
    'Guiricema',
    'Gurinhatã',
    'Heliodora',
    'Iapu',
    'Ibertioga',
    'Ibiá',
    'Ibiaí',
    'Ibiracatu',
    'Ibiraci',
    'Ibirité',
    'Ibitiúra de Minas',
    'Ibituruna',
    'Icaraí de Minas',
    'Igarapé',
    'Igaratinga',
    'Iguatama',
    'Ijaci',
    'Ilicínea',
    'Imbé de Minas',
    'Inconfidentes',
    'Indaiabira',
    'Indianópolis',
    'Ingaí',
    'Inhapim',
    'Inhaúma',
    'Inimutaba',
    'Ipaba',
    'Ipanema',
    'Ipatinga',
    'Ipiaçu',
    'Ipuiuna',
    'Iraí de Minas',
    'Itabira',
    'Itabirinha',
    'Itabirito',
    'Itacambira',
    'Itacarambi',
    'Itaguara',
    'Itaipé',
    'Itajubá',
    'Itamarandiba',
    'Itamarati de Minas',
    'Itambacuri',
    'Itambé do Mato Dentro',
    'Itamogi',
    'Itamonte',
    'Itanhandu',
    'Itanhomi',
    'Itaobim',
    'Itapagipe',
    'Itapecerica',
    'Itapeva',
    'Itatiaiuçu',
    'Itaú de Minas',
    'Itaúna',
    'Itaverava',
    'Itinga',
    'Itueta',
    'Ituiutaba',
    'Itumirim',
    'Iturama',
    'Itutinga',
    'Jaboticatubas',
    'Jacinto',
    'Jacuí',
    'Jacutinga',
    'Jaguaraçu',
    'Jaíba',
    'Jampruca',
    'Janaúba',
    'Januária',
    'Japaraíba',
    'Japonvar',
    'Jeceaba',
    'Jenipapo de Minas',
    'Jequeri',
    'Jequitaí',
    'Jequitibá',
    'Jequitinhonha',
    'Jesuânia',
    'Joaíma',
    'Joanésia',
    'João Monlevade',
    'João Pinheiro',
    'Joaquim Felício',
    'Jordânia',
    'José Gonçalves de Minas',
    'José Raydan',
    'Josenópolis',
    'Juatuba',
    'Juiz de Fora',
    'Juramento',
    'Juruaia',
    'Juvenília',
    'Ladainha',
    'Lagamar',
    'Lagoa da Prata',
    'Lagoa dos Patos',
    'Lagoa Dourada',
    'Lagoa Formosa',
    'Lagoa Grande',
    'Lagoa Santa',
    'Lajinha',
    'Lambari',
    'Lamim',
    'Laranjal',
    'Lassance',
    'Lavras',
    'Leandro Ferreira',
    'Leme do Prado',
    'Leopoldina',
    'Liberdade',
    'Lima Duarte',
    'Limeira do Oeste',
    'Lontra',
    'Luisburgo',
    'Luislândia',
    'Luminárias',
    'Luz',
    'Machacalis',
    'Machado',
    'Madre de Deus de Minas',
    'Malacacheta',
    'Mamonas',
    'Manga',
    'Manhuaçu',
    'Manhumirim',
    'Mantena',
    'Mar de Espanha',
    'Maravilhas',
    'Maria da Fé',
    'Mariana',
    'Marilac',
    'Mário Campos',
    'Maripá de Minas',
    'Marliéria',
    'Marmelópolis',
    'Martinho Campos',
    'Martins Soares',
    'Mata Verde',
    'Materlândia',
    'Mateus Leme',
    'Mathias Lobato',
    'Matias Barbosa',
    'Matias Cardoso',
    'Matipó',
    'Mato Verde',
    'Matozinhos',
    'Matutina',
    'Medeiros',
    'Medina',
    'Mendes Pimentel',
    'Mercês',
    'Mesquita',
    'Minas Novas',
    'Minduri',
    'Mirabela',
    'Miradouro',
    'Miraí',
    'Miravânia',
    'Moeda',
    'Moema',
    'Monjolos',
    'Monsenhor Paulo',
    'Montalvânia',
    'Monte Alegre de Minas',
    'Monte Azul',
    'Monte Belo',
    'Monte Carmelo',
    'Monte Formoso',
    'Monte Santo de Minas',
    'Monte Sião',
    'Montes Claros',
    'Montezuma',
    'Morada Nova de Minas',
    'Morro da Garça',
    'Morro do Pilar',
    'Munhoz',
    'Muriaé',
    'Mutum',
    'Muzambinho',
    'Nacip Raydan',
    'Nanuque',
    'Naque',
    'Natalândia',
    'Natércia',
    'Nazareno',
    'Nepomuceno',
    'Ninheira',
    'Nova Belém',
    'Nova Era',
    'Nova Lima',
    'Nova Módica',
    'Nova Ponte',
    'Nova Porteirinha',
    'Nova Resende',
    'Nova Serrana',
    'Nova União',
    'Novo Cruzeiro',
    'Novo Oriente de Minas',
    'Novorizonte',
    'Olaria',
    "Olhos-d'Água",
    'Olímpio Noronha',
    'Oliveira',
    'Oliveira Fortes',
    'Onça de Pitangui',
    'Oratórios',
    'Orizânia',
    'Ouro Branco',
    'Ouro Fino',
    'Ouro Preto',
    'Ouro Verde de Minas',
    'Padre Carvalho',
    'Padre Paraíso',
    'Pai Pedro',
    'Paineiras',
    'Pains',
    'Paiva',
    'Palma',
    'Palmópolis',
    'Papagaios',
    'Pará de Minas',
    'Paracatu',
    'Paraguaçu',
    'Paraisópolis',
    'Paraopeba',
    'Passa Quatro',
    'Passa Tempo',
    'Passa Vinte',
    'Passabém',
    'Passos',
    'Patis',
    'Patos de Minas',
    'Patrocínio do Muriaé',
    'Patrocínio',
    'Paula Cândido',
    'Paulistas',
    'Pavão',
    'Peçanha',
    'Pedra Azul',
    'Pedra Bonita',
    'Pedra do Anta',
    'Pedra do Indaiá',
    'Pedra Dourada',
    'Pedralva',
    'Pedras de Maria da Cruz',
    'Pedrinópolis',
    'Pedro Leopoldo',
    'Pedro Teixeira',
    'Pequeri',
    'Pequi',
    'Perdigão',
    'Perdizes',
    'Perdões',
    'Periquito',
    'Pescador',
    'Piau',
    'Piedade de Caratinga',
    'Piedade de Ponte Nova',
    'Piedade do Rio Grande',
    'Piedade dos Gerais',
    'Pimenta',
    "Pingo-d'Água",
    'Pintópolis',
    'Piracema',
    'Pirajuba',
    'Piranga',
    'Piranguçu',
    'Piranguinho',
    'Pirapetinga',
    'Pirapora',
    'Piraúba',
    'Pitangui',
    'Piumhi',
    'Planura',
    'Poço Fundo',
    'Poços de Caldas',
    'Pocrane',
    'Pompéu',
    'Ponte Nova',
    'Ponto Chique',
    'Ponto dos Volantes',
    'Porteirinha',
    'Porto Firme',
    'Poté',
    'Pouso Alegre',
    'Pouso Alto',
    'Prados',
    'Prata',
    'Pratápolis',
    'Pratinha',
    'Presidente Bernardes',
    'Presidente Juscelino',
    'Presidente Kubitschek',
    'Presidente Olegário',
    'Prudente de Morais',
    'Quartel Geral',
    'Queluzito',
    'Raposos',
    'Raul Soares',
    'Recreio',
    'Reduto',
    'Resende Costa',
    'Resplendor',
    'Ressaquinha',
    'Riachinho',
    'Riacho dos Machados',
    'Ribeirão das Neves',
    'Ribeirão Vermelho',
    'Rio Acima',
    'Rio Casca',
    'Rio do Prado',
    'Rio Doce',
    'Rio Espera',
    'Rio Manso',
    'Rio Novo',
    'Rio Paranaíba',
    'Rio Pardo de Minas',
    'Rio Piracicaba',
    'Rio Pomba',
    'Rio Preto',
    'Rio Vermelho',
    'Ritápolis',
    'Rochedo de Minas',
    'Rodeiro',
    'Romaria',
    'Rosário da Limeira',
    'Rubelita',
    'Rubim',
    'Sabará',
    'Sabinópolis',
    'Sacramento',
    'Salinas',
    'Salto da Divisa',
    'Santa Bárbara',
    'Santa Bárbara do Leste',
    'Santa Bárbara do Monte Verde',
    'Santa Bárbara do Tugúrio',
    'Santa Cruz de Minas',
    'Santa Cruz de Salinas',
    'Santa Cruz do Escalvado',
    'Santa Efigênia de Minas',
    'Santa Fé de Minas',
    'Santa Helena de Minas',
    'Santa Juliana',
    'Santa Luzia',
    'Santa Margarida',
    'Santa Maria de Itabira',
    'Santa Maria do Salto',
    'Santa Maria do Suaçuí',
    'Santa Rita de Caldas',
    'Santa Rita de Ibitipoca',
    'Santa Rita de Jacutinga',
    'Santa Rita de Minas',
    'Santa Rita do Itueto',
    'Santa Rita do Sapucaí',
    'Santa Rosa da Serra',
    'Santa Vitória',
    'Santana da Vargem',
    'Santana de Cataguases',
    'Santana de Pirapama',
    'Santana do Deserto',
    'Santana do Garambéu',
    'Santana do Jacaré',
    'Santana do Manhuaçu',
    'Santana do Paraíso',
    'Santana do Riacho',
    'Santana dos Montes',
    'Santo Antônio do Amparo',
    'Santo Antônio do Aventureiro',
    'Santo Antônio do Grama',
    'Santo Antônio do Itambé',
    'Santo Antônio do Jacinto',
    'Santo Antônio do Monte',
    'Santo Antônio do Retiro',
    'Santo Antônio do Rio Abaixo',
    'Santo Hipólito',
    'Santos Dumont',
    'São Bento Abade',
    'São Brás do Suaçuí',
    'São Domingos das Dores',
    'São Domingos do Prata',
    'São Félix de Minas',
    'São Francisco',
    'São Francisco de Paula',
    'São Francisco de Sales',
    'São Francisco do Glória',
    'São Geraldo',
    'São Geraldo da Piedade',
    'São Geraldo do Baixio',
    'São Gonçalo do Abaeté',
    'São Gonçalo do Pará',
    'São Gonçalo do Rio Abaixo',
    'São Gonçalo do Rio Preto',
    'São Gonçalo do Sapucaí',
    'São Gotardo',
    'São João Batista do Glória',
    'São João da Lagoa',
    'São João da Mata',
    'São João da Ponte',
    'São João das Missões',
    'São João del-Rei',
    'São João do Manhuaçu',
    'São João do Manteninha',
    'São João do Oriente',
    'São João do Pacuí',
    'São João do Paraíso',
    'São João Evangelista',
    'São João Nepomuceno',
    'São Joaquim de Bicas',
    'São José da Barra',
    'São José da Lapa',
    'São José da Safira',
    'São José da Varginha',
    'São José do Alegre',
    'São José do Divino',
    'São José do Goiabal',
    'São José do Jacuri',
    'São José do Mantimento',
    'São Lourenço',
    'São Miguel do Anta',
    'São Pedro da União',
    'São Pedro do Suaçuí',
    'São Pedro dos Ferros',
    'São Romão',
    'São Roque de Minas',
    'São Sebastião da Bela Vista',
    'São Sebastião da Vargem Alegre',
    'São Sebastião do Anta',
    'São Sebastião do Maranhão',
    'São Sebastião do Oeste',
    'São Sebastião do Paraíso',
    'São Sebastião do Rio Preto',
    'São Sebastião do Rio Verde',
    'São Tiago',
    'São Tomás de Aquino',
    'São Tomé das Letras',
    'São Vicente de Minas',
    'Sapucaí-Mirim',
    'Sardoá',
    'Sarzedo',
    'Sem-Peixe',
    'Senador Amaral',
    'Senador Cortes',
    'Senador Firmino',
    'Senador José Bento',
    'Senador Modestino Gonçalves',
    'Senhora de Oliveira',
    'Senhora do Porto',
    'Senhora dos Remédios',
    'Sericita',
    'Seritinga',
    'Serra Azul de Minas',
    'Serra da Saudade',
    'Serra do Salitre',
    'Serra dos Aimorés',
    'Serrania',
    'Serranópolis de Minas',
    'Serranos',
    'Serro',
    'Sete Lagoas',
    'Setubinha',
    'Silveirânia',
    'Silvianópolis',
    'Simão Pereira',
    'Simonésia',
    'Sobrália',
    'Soledade de Minas',
    'Tabuleiro',
    'Taiobeiras',
    'Taparuba',
    'Tapira',
    'Tapiraí',
    'Taquaraçu de Minas',
    'Tarumirim',
    'Teixeiras',
    'Teófilo Otoni',
    'Timóteo',
    'Tiradentes',
    'Tiros',
    'Tocantins',
    'Tocos do Moji',
    'Toledo',
    'Tombos',
    'Três Corações',
    'Três Marias',
    'Três Pontas',
    'Tumiritinga',
    'Tupaciguara',
    'Turmalina',
    'Turvolândia',
    'Ubá',
    'Ubaí',
    'Ubaporanga',
    'Uberaba',
    'Uberlândia',
    'Umburatiba',
    'Unaí',
    'União de Minas',
    'Uruana de Minas',
    'Urucânia',
    'Urucuia',
    'Vargem Alegre',
    'Vargem Bonita',
    'Vargem Grande do Rio Pardo',
    'Varginha',
    'Varjão de Minas',
    'Várzea da Palma',
    'Varzelândia',
    'Vazante',
    'Verdelândia',
    'Veredinha',
    'Veríssimo',
    'Vermelho Novo',
    'Vespasiano',
    'Viçosa',
    'Vieiras',
    'Virgem da Lapa',
    'Virgínia',
    'Virginópolis',
    'Virgolândia',
    'Visconde do Rio Branco',
    'Volta Grande',
    'Wenceslau Braz',
  ],
  es: [
    'Serra',
    'Vila Velha',
    'Cariacica',
    'Vitória',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'Guarapari',
    'São Mateus',
    'Colatina',
    'Aracruz',
    'Viana',
    'Nova Venécia',
    'Barra de São Francisco',
    'Marataízes',
    'Santa Maria de Jetibá',
    'Itapemirim',
    'Castelo',
    'Domingos Martins',
    'São Gabriel da Palha',
    'Afonso Cláudio',
    'Baixo Guandu',
    'Anchieta',
    'Guaçuí',
    'Alegre',
    'Jaguaré',
    'Iúna',
    'Conceição da Barra',
    'Sooretama',
    'Ibatiba',
    'Mimoso do Sul',
    'Pinheiros',
    'Venda Nova do Imigrante',
    'Santa Teresa',
    'Piúma',
    'Ecoporanga',
    'Pedro Canário',
    'Vargem Alta',
    'Rio Bananal',
    'Montanha',
    'Pancas',
    'Muniz Freire',
    'Fundão',
    'Marechal Floriano',
    'João Neiva',
    'Alfredo Chaves',
    'Muqui',
    'Vila Valério',
    'Irupi',
    'Presidente Kennedy',
    'Boa Esperança',
    'Itaguaçu',
    'Santa Leopoldina',
    'Brejetuba',
    'Mantenópolis',
    'Iconha',
    'Marilândia',
    'Água Doce do Norte',
    'Conceição do Castelo',
    'Ibiraçu',
    'Jerônimo Monteiro',
    'Laranja da Terra',
    'Rio Novo do Sul',
    'Governador Lindenberg',
    'São Roque do Canaã',
    'São José do Calçado',
    'Itarana',
    'Atílio Vivácqua',
    'Bom Jesus do Norte',
    'Águia Branca',
    'Ibitirama',
    'Vila Pavão',
    'São Domingos do Norte',
    'Alto Rio Novo',
    'Apiacá',
    'Dores do Rio Preto',
    'Ponto Belo',
    'Mucurici',
    'Divino de São Lourenço',
  ],
  rj: [
    'Angra dos Reis',
    'Aperibé',
    'Araruama',
    'Areal',
    'Armação dos Búzios',
    'Arraial do Cabo',
    'Barra do Piraí',
    'Barra Mansa',
    'Belford Roxo',
    'Bom Jardim',
    'Bom Jesus do Itabapoana',
    'Cabo Frio',
    'Cachoeiras de Macacu',
    'Cambuci',
    'Campos dos Goytacazes',
    'Cantagalo',
    'Carapebus',
    'Cardoso Moreira',
    'Carmo',
    'Casimiro de Abreu',
    'Comendador Levy Gasparian',
    'Conceição de Macabu',
    'Cordeiro',
    'Duas Barras',
    'Duque de Caxias',
    'Engenheiro Paulo de Frontin',
    'Guapimirim',
    'Iguaba Grande',
    'Itaboraí',
    'Itaguaí',
    'Italva',
    'Itaocara',
    'Itaperuna',
    'Itatiaia',
    'Japeri',
    'Laje do Muriaé',
    'Macaé',
    'Macuco',
    'Magé',
    'Mangaratiba',
    'Maricá',
    'Mendes',
    'Mesquita',
    'Miguel Pereira',
    'Miracema',
    'Natividade',
    'Nilópolis',
    'Niterói',
    'Nova Friburgo',
    'Nova Iguaçu',
    'Paracambi',
    'Paraíba do Sul',
    'Paraty',
    'Paty do Alferes',
    'Petrópolis',
    'Pinheiral',
    'Piraí',
    'Porciúncula',
    'Porto Real',
    'Quatis',
    'Queimados',
    'Quissamã',
    'Resende',
    'Rio Bonito',
    'Rio Claro',
    'Rio das Flores',
    'Rio das Ostras',
    'Rio de Janeiro',
    'Santa Maria Madalena',
    'Santo Antônio de Pádua',
    'São Fidélis',
    'São Francisco de Itabapoana',
    'São Gonçalo',
    'São João da Barra',
    'São João de Meriti',
    'São José de Ubá',
    'São José do Vale do Rio Preto',
    'São Pedro da Aldeia',
    'São Sebastião do Alto',
    'Sapucaia',
    'Saquarema',
    'Seropédica',
    'Silva Jardim',
    'Sumidouro',
    'Tanguá',
    'Teresópolis',
    'Trajano de Moraes',
    'Três Rios',
    'Valença',
    'Varre-Sai',
    'Vassouras',
    'Volta Redonda',
  ],
  ms: [
    'Campo Grande',
    'Dourados',
    'Três Lagoas',
    'Corumbá',
    'Ponta Porã',
    'Naviraí',
    'Nova Andradina',
    'Sidrolândia',
    'Aquidauana',
    'Maracaju',
    'Paranaíba',
    'Amambai',
    'Rio Brilhante',
    'Coxim',
    'Chapadão do Sul',
    'Caarapó',
    'São Gabriel do Oeste',
    'Ivinhema',
    'Aparecida do Taboado',
    'Costa Rica',
    'Miranda',
    'Itaporã',
    'Anastácio',
    'Jardim',
    'Bonito',
    'Ribas do Rio Pardo',
    'Bataguassu',
    'Nova Alvorada do Sul',
    'Bela Vista',
    'Ladário',
    'Cassilândia',
    'Fátima do Sul',
    'Rio Verde de Mato Grosso',
    'Itaquiraí',
    'Mundo Novo',
    'Terenos',
    'Água Clara',
    'Sonora',
    'Coronel Sapucaia',
    'Iguatemi',
    'Deodápolis',
    'Camapuã',
    'Nioaque',
    'Paranhos',
    'Porto Murtinho',
    'Brasilândia',
    'Eldorado',
    'Dois Irmãos do Buriti',
    'Sete Quedas',
    'Tacuru',
    'Aral Moreira',
    'Angélica',
    'Batayporã',
    'Glória de Dourados',
    'Guia Lopes da Laguna',
    'Antônio João',
    'Bodoquena',
    'Inocência',
    'Japorã',
    'Selvíria',
    'Bandeirantes',
    'Anaurilândia',
    'Jaraguari',
    'Santa Rita do Pardo',
    'Pedro Gomes',
    'Laguna Carapã',
    'Juti',
    'Vicentina',
    'Douradina',
    'Paraíso das Águas',
    'Rochedo',
    'Caracol',
    'Rio Negro',
    'Corguinho',
    'Novo Horizonte do Sul',
    'Alcinópolis',
    'Taquarussu',
    'Jateí',
    'Figueirão',
  ],
  sp: [
    'Adamantina',
    'Adolfo',
    'Aguaí',
    'Águas da Prata',
    'Águas de Lindóia',
    'Águas de Santa Bárbara',
    'Águas de São Pedro',
    'Agudos',
    'Alambari',
    'Alfredo Marcondes',
    'Altair',
    'Altinópolis',
    'Alto Alegre',
    'Alumínio',
    'Álvares Florence',
    'Álvares Machado',
    'Álvaro de Carvalho',
    'Alvinlândia',
    'Americana',
    'Américo Brasiliense',
    'Américo de Campos',
    'Amparo',
    'Analândia',
    'Andradina',
    'Angatuba',
    'Anhembi',
    'Anhumas',
    'Aparecida',
    "Aparecida d'Oeste",
    'Apiaí',
    'Araçariguama',
    'Araçatuba',
    'Araçoiaba da Serra',
    'Aramina',
    'Arandu',
    'Arapeí',
    'Araraquara',
    'Araras',
    'Arco-Íris',
    'Arealva',
    'Areias',
    'Areiópolis',
    'Ariranha',
    'Artur Nogueira',
    'Arujá',
    'Aspásia',
    'Assis',
    'Atibaia',
    'Auriflama',
    'Avaí',
    'Avanhandava',
    'Avaré',
    'Bady Bassitt',
    'Balbinos',
    'Bálsamo',
    'Bananal',
    'Barão de Antonina',
    'Barbosa',
    'Bariri',
    'Barra Bonita',
    'Barra do Chapéu',
    'Barra do Turvo',
    'Barretos',
    'Barrinha',
    'Barueri',
    'Bastos',
    'Batatais',
    'Bauru',
    'Bebedouro',
    'Bento de Abreu',
    'Bernardino de Campos',
    'Bertioga',
    'Bilac',
    'Birigui',
    'Biritiba Mirim',
    'Boa Esperança do Sul',
    'Bocaina',
    'Bofete',
    'Boituva',
    'Bom Jesus dos Perdões',
    'Bom Sucesso de Itararé',
    'Borá',
    'Boraceia',
    'Borborema',
    'Borebi',
    'Botucatu',
    'Bragança Paulista',
    'Braúna',
    'Brejo Alegre',
    'Brodowski',
    'Brotas',
    'Buri',
    'Buritama',
    'Buritizal',
    'Cabrália Paulista',
    'Cabreúva',
    'Caçapava',
    'Cachoeira Paulista',
    'Caconde',
    'Cafelândia',
    'Caiabu',
    'Caieiras',
    'Caiuá',
    'Cajamar',
    'Cajati',
    'Cajobi',
    'Cajuru',
    'Campina do Monte Alegre',
    'Campinas',
    'Campo Limpo Paulista',
    'Campos do Jordão',
    'Campos Novos Paulista',
    'Cananéia',
    'Canas',
    'Cândido Mota',
    'Cândido Rodrigues',
    'Canitar',
    'Capão Bonito',
    'Capela do Alto',
    'Capivari',
    'Caraguatatuba',
    'Carapicuíba',
    'Cardoso',
    'Casa Branca',
    'Cássia dos Coqueiros',
    'Castilho',
    'Catanduva',
    'Catiguá',
    'Cedral',
    'Cerqueira César',
    'Cerquilho',
    'Cesário Lange',
    'Charqueada',
    'Chavantes',
    'Clementina',
    'Colina',
    'Colômbia',
    'Conchal',
    'Conchas',
    'Cordeirópolis',
    'Coroados',
    'Coronel Macedo',
    'Corumbataí',
    'Cosmópolis',
    'Cosmorama',
    'Cotia',
    'Cravinhos',
    'Cristais Paulista',
    'Cruzália',
    'Cruzeiro',
    'Cubatão',
    'Cunha',
    'Descalvado',
    'Diadema',
    'Dirce Reis',
    'Divinolândia',
    'Dobrada',
    'Dois Córregos',
    'Dolcinópolis',
    'Dourado',
    'Dracena',
    'Duartina',
    'Dumont',
    'Echaporã',
    'Eldorado',
    'Elias Fausto',
    'Elisiário',
    'Embaúba',
    'Embu das Artes',
    'Embu-Guaçu',
    'Emilianópolis',
    'Engenheiro Coelho',
    'Espírito Santo do Pinhal',
    'Espírito Santo do Turvo',
    'Estiva Gerbi',
    'Estrela do Norte',
    "Estrela d'Oeste",
    'Euclides da Cunha Paulista',
    'Fartura',
    'Fernando Prestes',
    'Fernandópolis',
    'Fernão',
    'Ferraz de Vasconcelos',
    'Flora Rica',
    'Floreal',
    'Flórida Paulista',
    'Florínea',
    'Franca',
    'Francisco Morato',
    'Franco da Rocha',
    'Gabriel Monteiro',
    'Gália',
    'Garça',
    'Gastão Vidigal',
    'Gavião Peixoto',
    'General Salgado',
    'Getulina',
    'Glicério',
    'Guaiçara',
    'Guaimbê',
    'Guaíra',
    'Guapiaçu',
    'Guapiara',
    'Guará',
    'Guaraçaí',
    'Guaraci',
    "Guarani d'Oeste",
    'Guarantã',
    'Guararapes',
    'Guararema',
    'Guaratinguetá',
    'Guareí',
    'Guariba',
    'Guarujá',
    'Guarulhos',
    'Guatapará',
    'Guzolândia',
    'Herculândia',
    'Holambra',
    'Hortolândia',
    'Iacanga',
    'Iacri',
    'Iaras',
    'Ibaté',
    'Ibirá',
    'Ibirarema',
    'Ibitinga',
    'Ibiúna',
    'Icém',
    'Iepê',
    'Igaraçu do Tietê',
    'Igarapava',
    'Igaratá',
    'Iguape',
    'Ilha Comprida',
    'Ilha Solteira',
    'Ilhabela',
    'Indaiatuba',
    'Indiana',
    'Indiaporã',
    'Inúbia Paulista',
    'Ipaussu',
    'Iperó',
    'Ipeúna',
    'Ipiguá',
    'Iporanga',
    'Ipuã',
    'Iracemápolis',
    'Irapuã',
    'Irapuru',
    'Itaberá',
    'Itaí',
    'Itajobi',
    'Itaju',
    'Itanhaém',
    'Itaoca',
    'Itapecerica da Serra',
    'Itapetininga',
    'Itapeva',
    'Itapevi',
    'Itapira',
    'Itapirapuã Paulista',
    'Itápolis',
    'Itaporanga',
    'Itapuí',
    'Itapura',
    'Itaquaquecetuba',
    'Itararé',
    'Itariri',
    'Itatiba',
    'Itatinga',
    'Itirapina',
    'Itirapuã',
    'Itobi',
    'Itu',
    'Itupeva',
    'Ituverava',
    'Jaborandi',
    'Jaboticabal',
    'Jacareí',
    'Jaci',
    'Jacupiranga',
    'Jaguariúna',
    'Jales',
    'Jambeiro',
    'Jandira',
    'Jardinópolis',
    'Jarinu',
    'Jaú',
    'Jeriquara',
    'Joanópolis',
    'João Ramalho',
    'José Bonifácio',
    'Júlio Mesquita',
    'Jumirim',
    'Jundiaí',
    'Junqueirópolis',
    'Juquiá',
    'Juquitiba',
    'Lagoinha',
    'Laranjal Paulista',
    'Lavínia',
    'Lavrinhas',
    'Leme',
    'Lençóis Paulista',
    'Limeira',
    'Lindoia',
    'Lins',
    'Lorena',
    'Lourdes',
    'Louveira Louveira',
    'Lucélia',
    'Lucianópolis',
    'Luiz Antônio',
    'Luiziânia',
    'Lupércio',
    'Lutécia',
    'Macatuba',
    'Macaubal',
    'Macedônia',
    'Magda',
    'Mairinque',
    'Mairiporã',
    'Manduri',
    'Marabá Paulista',
    'Maracaí',
    'Marapoama',
    'Mariápolis',
    'Marília',
    'Marinópolis',
    'Martinópolis',
    'Matão',
    'Mauá',
    'Mendonça',
    'Meridiano',
    'Mesópolis',
    'Miguelópolis',
    'Mineiros do Tietê',
    'Mira Estrela',
    'Miracatu',
    'Mirandópolis',
    'Mirante do Paranapanema',
    'Mirassol',
    'Mirassolândia',
    'Mococa',
    'Mogi das Cruzes',
    'Mogi Guaçu',
    'Mogi Mirim',
    'Mombuca',
    'Monções',
    'Mongaguá',
    'Monte Alegre do Sul',
    'Monte Alto',
    'Monte Aprazível',
    'Monte Azul Paulista',
    'Monte Castelo',
    'Monte Mor',
    'Monteiro Lobato',
    'Morro Agudo',
    'Morungaba',
    'Motuca',
    'Murutinga do Sul',
    'Nantes',
    'Narandiba',
    'Natividade da Serra',
    'Nazaré Paulista',
    'Neves Paulista',
    'Nhandeara',
    'Nipoã',
    'Nova Aliança',
    'Nova Campina',
    'Nova Canaã Paulista',
    'Nova Castilho',
    'Nova Europa',
    'Nova Granada',
    'Nova Guataporanga',
    'Nova Independência',
    'Nova Luzitânia',
    'Nova Odessa',
    'Novais',
    'Novo Horizonte',
    'Nuporanga',
    'Ocauçu',
    'Óleo',
    'Olímpia',
    'Onda Verde',
    'Oriente',
    'Orindiúva',
    'Orlândia',
    'Osasco',
    'Oscar Bressane',
    'Osvaldo Cruz',
    'Ourinhos',
    'Ouro Verde',
    'Ouroeste',
    'Pacaembu',
    'Palestina',
    'Palmares Paulista',
    "Palmeira d'Oeste",
    'Palmital',
    'Panorama',
    'Paraguaçu Paulista',
    'Paraibuna Paraibuna',
    'Paraíso',
    'Paranapanema',
    'Paranapuã',
    'Parapuã',
    'Pardinho',
    'Pariquera-Açu',
    'Parisi',
    'Patrocínio Paulista',
    'Paulicéia',
    'Paulínia',
    'Paulistânia',
    'Paulo de Faria',
    'Pederneiras',
    'Pedra Bela',
    'Pedranópolis',
    'Pedregulho',
    'Pedreira',
    'Pedrinhas Paulista',
    'Pedro de Toledo',
    'Penápolis',
    'Pereira Barreto',
    'Pereiras',
    'Peruíbe',
    'Piacatu',
    'Piedade',
    'Pilar do Sul',
    'Pindamonhangaba',
    'Pindorama',
    'Pinhalzinho',
    'Piquerobi',
    'Piquete',
    'Piracaia',
    'Piracicaba',
    'Piraju',
    'Pirajuí',
    'Pirangi',
    'Pirapora do Bom Jesus',
    'Pirapozinho',
    'Pirassununga',
    'Piratininga',
    'Pitangueiras',
    'Planalto',
    'Platina',
    'Poá',
    'Poloni',
    'Pompeia',
    'Pongaí',
    'Pontal',
    'Pontalinda',
    'Pontes Gestal',
    'Populina',
    'Porangaba',
    'Porto Feliz',
    'Porto Ferreira',
    'Potim',
    'Potirendaba',
    'Pracinha',
    'Pradópolis',
    'Praia Grande',
    'Pratânia',
    'Presidente Alves',
    'Presidente Bernardes',
    'Presidente Epitácio',
    'Presidente Prudente',
    'Presidente Venceslau',
    'Promissão',
    'Quadra',
    'Quatá',
    'Queiroz',
    'Queluz',
    'Quintana',
    'Rafard',
    'Rancharia',
    'Redenção da Serra',
    'Regente Feijó',
    'Reginópolis',
    'Registro',
    'Restinga',
    'Ribeira',
    'Ribeirão Bonito',
    'Ribeirão Branco',
    'Ribeirão Corrente',
    'Ribeirão do Sul',
    'Ribeirão dos Índios',
    'Ribeirão Grande',
    'Ribeirão Pires',
    'Ribeirão Preto',
    'Rifaina',
    'Rincão',
    'Rinópolis',
    'Rio Claro',
    'Rio das Pedras',
    'Rio Grande da Serra',
    'Riolândia',
    'Riversul',
    'Rosana',
    'Roseira',
    'Rubiácea',
    'Rubineia',
    'Sabino',
    'Sagres',
    'Sales',
    'Sales Oliveira',
    'Salesópolis',
    'Salmourão',
    'Saltinho',
    'Salto',
    'Salto de Pirapora',
    'Salto Grande',
    'Sandovalina',
    'Santa Adélia',
    'Santa Albertina',
    "Santa Bárbara d'Oeste",
    'Santa Branca',
    "Santa Clara d'Oeste",
    'Santa Cruz da Conceição',
    'Santa Cruz da Esperança',
    'Santa Cruz das Palmeiras',
    'Santa Cruz do Rio Pardo',
    'Santa Ernestina',
    'Santa Fé do Sul',
    'Santa Gertrudes',
    'Santa Isabel',
    'Santa Lúcia',
    'Santa Maria da Serra',
    'Santa Mercedes',
    'Santa Rita do Passa Quatro',
    "Santa Rita d'Oeste",
    'Santa Rosa de Viterbo',
    'Santa Salete',
    'Santana da Ponte Pensa',
    'Santana de Parnaíba',
    'Santo Anastácio',
    'Santo André',
    'Santo Antônio da Alegria',
    'Santo Antônio de Posse',
    'Santo Antônio do Aracanguá',
    'Santo Antônio do Jardim',
    'Santo Antônio do Pinhal',
    'Santo Expedito',
    'Santópolis do Aguapeí',
    'Santos',
    'São Bento do Sapucaí',
    'São Bernardo do Campo',
    'São Caetano do Sul',
    'São Carlos',
    'São Francisco',
    'São João da Boa Vista',
    'São João das Duas Pontes',
    'São João de Iracema',
    "São João do Pau-d'Alho",
    'São Joaquim da Barra',
    'São José da Bela Vista',
    'São José do Barreiro',
    'São José do Rio Pardo',
    'São José do Rio Preto',
    'São José dos Campos',
    'São Lourenço da Serra',
    'São Luiz do Paraitinga',
    'São Manuel',
    'São Miguel Arcanjo',
    'São Paulo',
    'São Pedro',
    'São Pedro do Turvo',
    'São Roque',
    'São Sebastião',
    'São Sebastião da Grama',
    'São Simão',
    'São Vicente',
    'Sarapuí',
    'Sarutaiá',
    'Sebastianópolis do Sul',
    'Serra Azul',
    'Serra Negra',
    'Serrana',
    'Sertãozinho',
    'Sete Barras',
    'Severínia',
    'Silveiras',
    'Socorro',
    'Sorocaba',
    'Sud Mennucci',
    'Sumaré',
    'Suzanápolis',
    'Suzano',
    'Tabapuã',
    'Tabatinga',
    'Taboão da Serra',
    'Taciba',
    'Taguaí',
    'Taiaçu',
    'Taiúva',
    'Tambaú',
    'Tanabi',
    'Tapiraí',
    'Tapiratiba',
    'Taquaral',
    'Taquaritinga',
    'Taquarituba',
    'Taquarivaí',
    'Tarabai',
    'Tarumã',
    'Tatuí',
    'Taubaté',
    'Tejupá',
    'Teodoro Sampaio',
    'Terra Roxa',
    'Tietê',
    'Timburi',
    'Torre de Pedra',
    'Torrinha',
    'Trabiju',
    'Tremembé',
    'Três Fronteiras',
    'Tuiuti',
    'Tupã',
    'Tupi Paulista',
    'Turiúba',
    'Turmalina',
    'Ubarana',
    'Ubatuba',
    'Ubirajara',
    'Uchoa',
    'União Paulista',
    'Urânia',
    'Uru',
    'Urupês',
    'Valentim Gentil',
    'Valinhos',
    'Valparaíso',
    'Vargem',
    'Vargem Grande do Sul',
    'Vargem Grande Paulista',
    'Várzea Paulista',
    'Vera Cruz',
    'Vinhedo',
    'Viradouro',
    'Vista Alegre do Alto',
    'Vitória Brasil',
    'Votorantim',
    'Votuporanga',
    'Zacarias',
  ],
  pr: [
    'Foz do Iguaçu',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'São José dos Pinhais',
    'Foz do Iguaçu',
    'Colombo',
    'Guarapuava',
    'Araucária',
    'Toledo',
    'Fazenda Rio Grande',
    'Paranaguá',
    'Campo Largo',
    'Apucarana',
    'Pinhais',
    'Almirante Tamandaré',
    'Arapongas',
    'Piraquara',
    'Sarandi',
    'Umuarama',
    'Cambé',
    'Campo Mourão',
    'Francisco Beltrão',
    'Paranavaí',
    'Pato Branco',
    'Cianorte',
    'Telêmaco Borba',
    'Castro',
    'Rolândia',
    'Irati',
    'União da Vitória',
    'Marechal Cândido Rondon',
    'Ibiporã',
    'Prudentópolis',
    'Palmas',
    'Campina Grande do Sul',
    'Medianeira',
    'Santo Antônio da Platina',
    'Paiçandu',
    'Cornélio Procópio',
    'Lapa',
    'Dois Vizinhos',
    'São Mateus do Sul',
    'Guaratuba',
    'Jacarezinho',
    'Marialva',
    'Matinhos',
    'Rio Branco do Sul',
    'Assis Chateaubriand',
    'Mandaguari',
    'Jaguariaíva',
    'Palotina',
    'Palmeira',
    'Pitanga',
    'Ivaiporã',
    'Laranjeiras do Sul',
    'Guaíra',
    'Mandaguaçu',
    'Rio Negro',
    'Bandeirantes',
    'Itaperuçu',
    'Quedas do Iguaçu',
    'Pontal do Paraná',
    'Imbituva',
    'Campo Magro',
    'Pinhão',
    'São Miguel do Iguaçu',
    'Ibaiti',
    'Goioerê',
    'Mandirituba',
    'Nova Esperança',
    'Arapoti',
    'Santa Helena',
    'Astorga',
    'Ubiratã',
    'Reserva',
    'Santa Terezinha de Itaipu',
    'Ortigueira',
    'Quatro Barras',
    'Cruzeiro do Oeste',
    'Santo Antônio do Sudoeste',
    'Piraí do Sul',
    'Coronel Vivida',
    'Carambeí',
    'Loanda',
    'Cambará',
    'Colorado',
    'Siqueira Campos',
    'Jandaia do Sul',
    'Chopinzinho',
    'Capanema',
    'Tibagi',
    'Andirá',
    'Ampére',
    'Realeza',
    'Wenceslau Braz',
    'Contenda',
    'Cafelândia',
    'Altônia',
    'Matelândia',
    'Quitandinha',
    'Morretes',
    'Terra Roxa',
    'Antonina',
    'Tijucas do Sul',
    'Terra Boa',
    'Corbélia',
    'Sengés',
    'Mangueirinha',
    'Faxinal',
    'Cerro Azul',
    'Cruz Machado',
    'Sertanópolis',
    'Marmeleiro',
    'Tapejara',
    'Bituruna',
    'Cândido de Abreu',
    'Salto do Lontra',
    'Clevelândia',
    'Candói',
    'Terra Rica',
    'Bela Vista do Paraíso',
    'Capitão Leônidas Marques',
    'Rebouças',
    'Ipiranga',
    'Santa Izabel do Oeste',
    'Rio Azul',
    'Alto Paraná',
    'Assaí',
    'São João do Triunfo',
    'Curiúva',
    'Tamarana',
    'Carlópolis',
    'Paraíso do Norte',
    'Ivaí',
    'Araruna',
    'Peabirú',
    'Engenheiro Beltrão',
    'Campina da Lagoa',
    'Jaguapitã',
    'Mallet',
    'General Carneiro',
    'Iporã',
    'Manoel Ribas',
    'Imbaú',
    'Planalto',
    'Cantagalo',
    'Bocaiuva do Sul',
    'Rio Bonito do Iguaçu',
    'Balsa Nova',
    'Nova Londrina',
    'Piên',
    'Turvo',
    'Cidade Gaúcha',
    'Mamborê',
    'Ribeirão do Pinhal',
    'Teixeira Soares',
    'Palmital',
    'Jataizinho',
    'Porecatu',
    'Querência do Norte',
    'Guaraniaçu',
    'Santa Fé',
    "Itapejara d'Oeste",
    'Ventania',
    'Moreira Sales',
    'Três Barras do Paraná',
    'Joaquim Távora',
    'Céu Azul',
    'Santa Mariana',
    'Paranacity',
    'Nova Laranjeiras',
    'Alvorada do Sul',
    'Barbosa Ferraz',
    'Itaipulândia',
    'Pérola',
    'Uraí',
    'Jardim Alegre',
    'Primeiro de Maio',
    'São Jerônimo da Serra',
    'Inácio Martins',
    'São Pedro do Ivaí',
    'Mauá da Serra',
    'Centenário do Sul',
    'Missal',
    'Ribeirão Claro',
    'Nova Prata do Iguaçu',
    'Florestópolis',
    'Mariluz',
    'Barracão',
    'Nova Aurora',
    'São João',
    'Catanduvas',
    'Iretama',
    'Santa Tereza do Oeste',
    'São João do Ivaí',
    'Alto Piquiri',
    'Roncador',
    'Rondon',
    'Japurá',
    'Agudos do Sul',
    'Santa Maria do Oeste',
    "São Jorge d'Oeste",
    'Tunas do Paraná',
    'Douradina',
    'São Sebastião da Amoreira',
    'Congonhinhas',
    'Marilândia do Sul',
    'Guamiranga',
    'Califórnia',
    'Tuneiras do Oeste',
    'Santa Isabel do Ivaí',
    'Vera Cruz do Oeste',
    'Jesuítas',
    'Nova Santa Rosa',
    'Ivaté',
    'Nova Fátima',
    'Tupãssi',
    'Reserva do Iguaçu',
    'Campo do Tenente',
    'Cambira',
    'Tomazina',
    'Icaraíma',
    'Santa Cruz de Monte Castelo',
    'Figueira',
    'Guaraqueçaba',
    'Boa Vista da Aparecida',
    'Coronel Domingos Soares',
    'Quatiguá',
    'Antônio Olinto',
    'Abatiá',
    'Paulo Frontin',
    'Juranda',
    'Luiziana',
    'Bom Sucesso',
    'Verê',
    'Marilena',
    'Goioxim',
    'Jussara',
    'São Carlos do Ivaí',
    'Sabáudia',
    'Vitorino',
    'Floresta',
    'Renascença',
    'Sapopema',
    'Mariópolis',
    'Guairaçá',
    'Itambaracá',
    'Amaporã',
    'Ibema',
    'Formosa do Oeste',
    'Boa Ventura de São Roque',
    'Pinhalão',
    'Borrazópolis',
    "Pérola d'Oeste",
    'Perobal',
    'São José da Boa Vista',
    'Itambé',
    'Ouro Verde do Oeste',
    'Doutor Camargo',
    'Francisco Alves',
    'Paula Freitas',
    'Enéas Marques',
    'Nova Olímpia',
    'São João do Caiuá',
    'Adrianópolis',
    'São Tomé',
    'Pato Bragado',
    'São Pedro do Iguaçu',
    'Laranjal',
    'Mercedes',
    'Maria Helena',
    'Xambrê',
    'Saudade do Iguaçu',
    'Maripá',
    'Fernandes Pinheiro',
    'Guaraci',
    'São Jorge do Ivaí',
    'São Jorge do Patrocínio',
    'Doutor Ulysses',
    'Tapira',
    'Santo Inácio',
    'Presidente Castelo Branco',
    'Grandes Rios',
    'Braganey',
    'Jaboti',
    "Diamante D'Oeste",
    'Nova Tebas',
    'Tamboara',
    'Sertaneja',
    'Pranchita',
    'Honório Serpa',
    'Nova Esperança do Sudoeste',
    'Diamante do Norte',
    'Lupionópolis',
    'Janiópolis',
    'Japira',
    'Santana do Itararé',
    'Porto Amazonas',
    'Floraí',
    'Salto do Itararé',
    'Lobato',
    'Nova Cantu',
    'Fênix',
    'Lunardelli',
    'Marumbi',
    'Entre Rios do Oeste',
    'Rosário do Ivaí',
    'Flor da Serra do Sul',
    'Ramilândia',
    'Lindoeste',
    'Iguaraçu',
    'Indianópolis',
    'Foz do Jordão',
    'Serranópolis do Iguaçu',
    'Quinta do Sol',
    'Cruzeiro do Sul',
    'Itaguajé',
    'Quarto Centenário',
    'Nova Santa Bárbara',
    'Marquinho',
    'Planaltina do Paraná',
    'Cruzeiro do Iguaçu',
    'Rio Branco do Ivaí',
    'Porto Vitória',
    'Santa Mônica',
    'Virmond',
    'Quatro Pontes',
    'Munhoz de Melo',
    'Nossa Senhora das Graças',
    'Kaloré',
    'Boa Esperança',
    'Espigão Alto do Iguaçu',
    'Cafezal do Sul',
    'Leópolis',
    'Conselheiro Mairinck',
    'Atalaia',
    'Campina do Simão',
    'Prado Ferreira',
    'Santa Lúcia',
    'Guapirama',
    'Rancho Alegre',
    'Campo Bonito',
    'São José das Palmeiras',
    'Bom Jesus do Sul',
    'Nova América da Colina',
    'Ourizona',
    'Diamante do Sul',
    'Bela Vista da Caroba',
    'Salgado Filho',
    'Ivatuba',
    'Pitangueiras',
    'Paranapoema',
    'Santa Cecília do Pavão',
    'Jundiaí do Sul',
    'Bom Sucesso do Sul',
    'Santa Amélia',
    'Rio Bom',
    'Lidianópolis',
    'Mato Rico',
    'Porto Barreiro',
    'Inajá',
    'Corumbataí do Sul',
    'Farol',
    'Cafeara',
    'Arapuã',
    'Ângulo',
    'Cruzmaltina',
    'Sulina',
    'Godoy Moreira',
    'Novo Itacolomi',
    'Barra do Jacaré',
    'Anahy',
    'Pinhal de São Bento',
    'Flórida',
    'Itaúna do Sul',
    'Alto Paraíso',
    'Uniflor',
    'Santo Antônio do Caiuá',
    "Rancho Alegre D'Oeste",
    'Porto Rico',
    'Brasilândia do Sul',
    'Manfrinópolis',
    'Boa Esperança do Iguaçu',
    'São Pedro do Paraná',
    'Iguatu',
    'Guaporema',
    'Iracema do Oeste',
    'Mirador',
    'São Manoel do Paraná',
    'Santo Antônio do Paraíso',
    'Ariranha do Ivaí',
    'Miraselva',
    'Esperança Nova',
    'Santa Inês',
    'Altamira do Paraná',
    'Jardim Olinda',
    'Nova Aliança do Ivaí',
    'Curitiba',
  ],
  sc: [
    'Abdon Batista',
    'Abelardo Luz',
    'Agrolândia',
    'Agronômica',
    'Água Doce',
    'Águas de Chapecó',
    'Águas Frias',
    'Águas Mornas',
    'Alfredo Wagner',
    'Alto Bela Vista',
    'Anchieta',
    'Angelina',
    'Anita Garibaldi',
    'Anitápolis',
    'Antônio Carlos',
    'Apiúna',
    'Arabutã',
    'Araquari',
    'Araranguá',
    'Armazém',
    'Arroio Trinta',
    'Arvoredo',
    'Ascurra',
    'Atalanta',
    'Aurora',
    'Balneário Arroio do Silva',
    'Balneário Barra do Sul',
    'Balneário Camboriú',
    'Balneário Gaivota',
    'Balneário Piçarras',
    'Balneário Rincão',
    'Bandeirante',
    'Barra Bonita',
    'Barra Velha',
    'Bela Vista do Toldo',
    'Belmonte',
    'Benedito Novo',
    'Biguaçu',
    'Blumenau',
    'Bocaina do Sul',
    'Bom Jardim da Serra',
    'Bom Jesus',
    'Bom Jesus do Oeste',
    'Bom Retiro',
    'Bombinhas',
    'Botuverá',
    'Braço do Norte',
    'Braço do Trombudo',
    'Brunópolis',
    'Brusque',
    'Caçador',
    'Caibi',
    'Calmon',
    'Camboriú',
    'Campo Alegre',
    'Campo Belo do Sul',
    'Campo Erê',
    'Campos Novos',
    'Canelinha',
    'Canoinhas',
    'Capão Alto',
    'Capinzal',
    'Capivari de Baixo',
    'Catanduvas',
    'Caxambu do Sul',
    'Celso Ramos',
    'Cerro Negro',
    'Chapadão do Lageado',
    'Chapecó',
    'Cocal do Sul',
    'Concórdia',
    'Cordilheira Alta',
    'Coronel Freitas',
    'Coronel Martins',
    'Correia Pinto',
    'Corupá',
    'Criciúma',
    'Cunha Porã',
    'Cunhataí',
    'Curitibanos',
    'Descanso',
    'Dionísio Cerqueira',
    'Dona Emma',
    'Doutor Pedrinho',
    'Entre Rios',
    'Ermo',
    'Erval Velho',
    'Faxinal dos Guedes',
    'Flor do Sertão',
    'Florianópolis',
    'Formosa do Sul',
    'Forquilhinha',
    'Fraiburgo',
    'Frei Rogério',
    'Galvão',
    'Garopaba',
    'Garuva',
    'Gaspar',
    'Governador Celso Ramos',
    'Grão-Pará',
    'Gravatal',
    'Guabiruba',
    'Guaraciaba',
    'Guaramirim',
    'Guarujá do Sul',
    'Guatambu',
    "Herval d'Oeste",
    'Ibiam',
    'Ibicaré',
    'Ibirama',
    'Içara',
    'Ilhota',
    'Imaruí',
    'Imbituba',
    'Imbuia',
    'Indaial',
    'Iomerê',
    'Ipira',
    'Iporã do Oeste',
    'Ipuaçu',
    'Ipumirim',
    'Iraceminha',
    'Irani',
    'Irati',
    'Irineópolis',
    'Itá',
    'Itaiópolis',
    'Itajaí',
    'Itapema',
    'Itapiranga',
    'Itapoá',
    'Ituporanga',
    'Jaborá',
    'Jacinto Machado',
    'Jaguaruna',
    'Jaraguá do Sul',
    'Jardinópolis',
    'Joaçaba',
    'Joinville',
    'José Boiteux',
    'Jupiá',
    'Lacerdópolis',
    'Lages',
    'Laguna',
    'Lajeado Grande',
    'Laurentino',
    'Lauro Müller',
    'Lebon Régis',
    'Leoberto Leal',
    'Lindóia do Sul',
    'Lontras',
    'Luiz Alves',
    'Luzerna',
    'Macieira',
    'Mafra',
    'Major Gercino',
    'Major Vieira',
    'Maracajá',
    'Maravilha',
    'Marema',
    'Massaranduba',
    'Matos Costa',
    'Meleiro',
    'Mirim Doce',
    'Modelo',
    'Mondaí',
    'Monte Carlo',
    'Monte Castelo',
    'Morro da Fumaça',
    'Morro Grande',
    'Navegantes',
    'Nova Erechim',
    'Nova Itaberaba',
    'Nova Trento',
    'Nova Veneza',
    'Novo Horizonte',
    'Orleans',
    'Otacílio Costa',
    'Ouro',
    'Ouro Verde',
    'Paial',
    'Painel',
    'Palhoça',
    'Palma Sola',
    'Palmeira',
    'Palmitos',
    'Papanduva',
    'Paraíso',
    'Passo de Torres',
    'Passos Maia',
    'Paulo Lopes',
    'Pedras Grandes',
    'Penha',
    'Peritiba',
    'Pescaria Brava',
    'Petrolândia',
    'Pinhalzinho',
    'Pinheiro Preto',
    'Piratuba',
    'Planalto Alegre',
    'Pomerode',
    'Ponte Alta',
    'Ponte Alta do Norte',
    'Ponte Serrada',
    'Porto Belo',
    'Porto União',
    'Pouso Redondo',
    'Praia Grande',
    'Presidente Castello Branco',
    'Presidente Getúlio',
    'Presidente Nereu',
    'Princesa',
    'Quilombo',
    'Rancho Queimado',
    'Rio das Antas',
    'Rio do Campo',
    'Rio do Oeste',
    'Rio do Sul',
    'Rio dos Cedros',
    'Rio Fortuna',
    'Rio Negrinho',
    'Rio Rufino',
    'Riqueza',
    'Rodeio',
    'Romelândia',
    'Salete',
    'Saltinho',
    'Salto Veloso',
    'Sangão',
    'Santa Cecília',
    'Santa Helena',
    'Santa Rosa de Lima',
    'Santa Rosa do Sul',
    'Santa Terezinha',
    'Santa Terezinha do Progresso',
    'Santiago do Sul',
    'Santo Amaro da Imperatriz',
    'São Bento do Sul',
    'São Bernardino',
    'São Bonifácio',
    'São Carlos',
    'São Cristóvão do Sul',
    'São Domingos',
    'São Francisco do Sul',
    'São João Batista',
    'São João do Itaperiú',
    'São João do Oeste',
    'São João do Sul',
    'São Joaquim',
    'São José',
    'São José do Cedro',
    'São José do Cerrito',
    'São Lourenço do Oeste',
    'São Ludgero',
    'São Martinho',
    'São Miguel da Boa Vista',
    'São Miguel do Oeste',
    'São Pedro de Alcântara',
    'Saudades',
    'Schroeder',
    'Seara',
    'Serra Alta',
    'Siderópolis',
    'Sombrio',
    'Sul Brasil',
    'Taió',
    'Tangará',
    'Tigrinhos',
    'Tijucas',
    'Timbé do Sul',
    'Timbó',
    'Timbó Grande',
    'Três Barras',
    'Treviso',
    'Treze de Maio',
    'Treze Tílias',
    'Trombudo Central',
    'Tubarão',
    'Tunápolis',
    'Turvo',
    'União do Oeste',
    'Urubici',
    'Urupema',
    'Urussanga',
    'Vargeão',
    'Vargem',
    'Vargem Bonita',
    'Vidal Ramos',
    'Videira',
    'Vitor Meireles',
    'Witmarsum',
    'Xanxerê',
    'Xavantina',
    'Xaxim',
    'Zortéa',
  ],
  rs: [
    'Porto Alegre',
    'Caxias do Sul',
    'Canoas',
    'Pelotas',
    'Santa Maria',
    'Gravataí',
    'Novo Hamburgo',
    'Viamão',
    'São Leopoldo',
    'Passo Fundo',
    'Alvorada',
    'Cachoeirinha',
    'Santa Cruz do Sul',
    'Sapucaia do Sul',
    'Bento Gonçalves',
    'Bagé',
    'Uruguaiana',
    'Erechim',
    'Lajeado',
    'Guaíba Guaíba',
    'Ijuí',
    'Santana do Livramento',
    'Cachoeira do Sul',
    'Santa Rosa',
    'Santo Ângelo',
    'Esteio',
    'Sapiranga',
    'Alegrete',
    'Farroupilha',
    'Venâncio Aires',
    'Vacaria',
    'Montenegro',
    'Capão da Canoa',
    'Campo Bom',
    'Camaquã',
    'Carazinho',
    'São Borja',
    'Cruz Alta',
    'São Gabriel',
    'Tramandaí',
    'Taquara',
    'Parobé',
    'Canguçu',
    'Canela',
    'Santiago',
    'Estância Velha',
    'Osório',
    'Marau',
    'Panambi',
    'Santo Antônio da Patrulha',
    'São Lourenço do Sul',
    'Torres',
    'Gramado',
    'Eldorado do Sul',
    'Dom Pedrito',
    'Rosário do Sul',
    'Itaqui',
    'Charqueadas',
    'São Luiz Gonzaga',
    'Rio Pardo',
    'Garibaldi',
    'Portão',
    'Palmeira das Missões',
    'Igrejinha',
    'Teutônia',
    'Frederico Westphalen',
    'Caçapava do Sul',
    'Estrela',
    'Santa Vitória do Palmar',
    'Flores da Cunha',
    'Dois Irmãos',
    'Carlos Barbosa',
    'Soledade',
    'Nova Santa Rita',
    'Candelária',
    'Lagoa Vermelha',
    'Triunfo (Rio Grande do Sul) Triunfo',
    'Imbé',
    'Vera Cruz',
    'Jaguarão',
    'Capão do Leão',
    'Nova Prata',
    'São José do Norte',
    'Três Passos',
    'Guaporé',
    'Taquari',
    'Três de Maio',
    'Tapejara',
    'São Sebastião do Caí',
    'Três Coroas',
    'Veranópolis',
    'Encruzilhada do Sul',
    'Quaraí',
    'Nova Petrópolis',
    'Ivoti',
    'Encantado',
    'Sarandi',
    'Arroio do Meio',
    'São Francisco de Paula',
    'Ibirubá',
    'Rolante',
    'São Sepé',
    'São Marcos',
    'São Jerônimo',
    'Nova Hartz',
    'Tupanciretã',
    'Butiá',
    'Horizontina',
    'Júlio de Castilhos',
    'Não-Me-Toque',
    'São Francisco de Assis',
    'Arroio Grande',
    'Piratini',
    'Cidreira',
    'Serafina Corrêa',
    'Getúlio Vargas',
    'Xangri-lá',
    'Sananduva',
    'Agudo',
    'Giruá',
    'São Pedro do Sul',
    'Santo Cristo',
    'Espumoso',
    'Balneário Pinhal',
    'Restinga Sêca',
    'Tapes',
    'Arroio dos Ratos',
    'Tenente Portela',
    'Sobradinho',
    'Santo Augusto',
    'Feliz',
    'Nonoai',
    'Cerro Largo',
    'Bom Princípio',
    'Dom Feliciano',
    'Antônio Prado',
    'Crissiumal',
    'Palmares do Sul',
    'Bom Retiro do Sul',
    'Barra do Ribeiro',
    'Mostardas',
    'Arroio do Tigre',
    'Seberi',
    'Cruzeiro do Sul',
    'Pinheiro Machado',
    'Bom Jesus',
    'Capela de Santana',
    'Cacequi',
    'Arroio do Sal',
    'Três Cachoeiras',
    'Candiota',
    'Tapera',
    'Jaguari',
    'Roca Sales',
    'Planalto',
    'Constantina',
    'Arvorezinha',
    'Santo Antônio das Missões',
    'Terra de Areia',
    'Pantano Grande',
    'Salto do Jacuí',
    'Porto Xavier',
    'Ronda Alta',
    'Redentora',
    'Nova Bassano',
    'Vale do Sol',
    'Fontoura Xavier',
    'Chapada',
    'Casca',
    'Barros Cassal',
    'Cerro Grande do Sul',
    'Entre-Ijuís',
    'Catuípe',
    'Sinimbu',
    'Araricá',
    'Tuparendi',
    'Santa Bárbara do Sul',
    'São Vicente do Sul',
    'Paverama',
    'Palmitinho',
    'Glorinha',
    'Ametista do Sul',
    'General Câmara',
    'Trindade do Sul',
    'Minas do Leão',
    'Pedro Osório',
    'Iraí',
    'Maquiné',
    'Guarani das Missões',
    'Caraá',
    'Cristal',
    'Paraí',
    'Jóia',
    'Lavras do Sul',
    'Augusto Pestana',
    'Barão de Cotegipe',
    'Alpestre',
    'São Miguel das Missões',
    'Santana da Boa Vista',
    'Boa Vista do Buricá',
    'Santa Clara do Sul',
    'Salvador do Sul',
    'São José do Ouro',
    'Manoel Viana',
    'Erval Seco',
    'Ibiraiaras',
    'Ajuricaba',
    'Faxinal do Soturno',
    'Rodeio Bonito',
    'Roque Gonzales',
    'Paraíso do Sul',
    'Aratiba',
    'Barão',
    'Independência',
    'Formigueiro',
    'Condor',
    'Cambará do Sul',
    'Santa Maria do Herval',
    'Cândido Godói',
    'Chuí',
    'Boqueirão do Leão',
    'Lindolfo Collor',
    'Herval',
    'Coronel Bicaco',
    'Alecrim',
    'Vale Real',
    'Morro Redondo',
    'Morro Reuter',
    'Passo do Sobrado',
    'Segredo',
    'Hulha Negra',
    'Anta Gorda',
    'Bossoroca',
    'Barão do Triunfo',
    'Campina das Missões',
    'Sertão Santana',
    'São Paulo das Missões',
    'Cerrito',
    'Machadinho',
    'Gaurama',
    'Nova Palma',
    'Estação',
    'Itaara',
    'Tucunduva',
    'Sertão',
    'São Martinho',
    'Harmonia',
    'Picada Café',
    'Lagoão',
    'Progresso',
    'Ipê',
    'Amaral Ferrador',
    'Sentinela do Sul',
    'Campinas do Sul',
    'Tavares',
    'Tiradentes do Sul',
    'São Nicolau',
    'Selbach',
    'Tupandi',
    'Rondinha',
    'Campo Novo',
    'Brochier',
    'Nova Araçá',
    'Erval Grande',
    'Nova Esperança do Sul',
    'Mato Leitão',
    'Caiçara',
    'Barracão',
    'Liberato Salzano',
    'Viadutos',
    'Três Palmeiras',
    'Caibaté',
    'Mata',
    'Humaitá',
    'Vicente Dutra',
    'Cacique Doble',
    'Muçum',
    'Chuvisca',
    'Pinheirinho do Vale',
    'Ibiaçá',
    'Fortaleza dos Valos',
    'Riozinho',
    'Doutor Maurício Cardoso',
    'São João da Urtiga',
    'Tabaí',
    'São José do Hortêncio',
    'Miraguaí',
    'Maçambará',
    'Vila Maria',
    'Porto Lucena',
    'David Canabarro',
    'Marcelino Ramos',
    'Pareci Novo',
    'Fazenda Vilanova',
    'Novo Barreiro',
    'Barra do Quaraí',
    'Maximiliano de Almeida',
    'São José dos Ausentes',
    'Aceguá',
    'Ilópolis',
    'Ciríaco',
    'Arambaré',
    'Capivari do Sul',
    'Passa-Sete',
    'Marques de Souza',
    'Mariana Pimentel',
    'Chiapetta',
    'Água Santa',
    'Quinze de Novembro',
    'Vila Nova do Sul',
    'Cotiporã',
    'Pinhal Grande',
    'Cerro Branco',
    'Jaboticaba',
    'Putinga',
    'Pejuçara',
    'Ibarama',
    'Ibirapuitã',
    'Jaquirana',
    'Tunas',
    'Alegria',
    'Vila Flores',
    'Paim Filho',
    'Campos Borges',
    'Novo Cabrais',
    'São Pedro da Serra',
    'Nova Roma do Sul',
    'Turuçu',
    'Severiano de Almeida',
    'Áurea',
    'Jari',
    'Jacutinga',
    'Gramado Xavier',
    'Pontão',
    'Braga',
    'Tio Hugo',
    'São Valentim',
    'Vitória das Missões',
    'Colorado',
    'Campestre da Serra',
    'Esperança do Sul',
    'Itatiba do Sul',
    'Novo Machado',
    'Esmeralda',
    'Monte Alegre dos Campos',
    'Nova Alvorada',
    'Barra do Guarita',
    'Vale Verde',
    'Mampituba',
    'Capão do Cipó',
    'Taquaruçu do Sul',
    'Westfália',
    'Dois Lajeados',
    'Imigrante',
    'Dona Francisca',
    'Presidente Lucena',
    'Alto Feliz',
    'Morrinhos do Sul',
    'Estrela Velha',
    'São Pedro do Butiá',
    'Nova Candelária',
    'Erebango',
    'Nova Bréscia',
    'Ernestina',
    'Caseiros',
    'Itacurubi',
    'Camargo',
    'Pinhal',
    'Capitão',
    'São Jorge',
    'Muitos Capões',
    'Salvador das Missões',
    'Rio dos Índios',
    'Coronel Barros',
    'São Martinho da Serra',
    'Dilermando de Aguiar',
    'Vista Gaúcha',
    'Victor Graeff',
    'Boa Vista do Sul',
    'Charrua',
    'Três Forquilhas',
    'Mormaço',
    'São Domingos do Sul',
    'Derrubadas',
    'Pinto Bandeira',
    'Centenário',
    'Sede Nova',
    'Cristal do Sul',
    'Garruchos',
    'Entre Rios do Sul',
    'Senador Salgado Filho',
    'Coxilha',
    'Vista Alegre',
    'São João do Polêsine',
    'Itati',
    'Eugênio de Castro',
    'Lajeado do Bugre',
    'Arroio do Padre',
    'Santa Margarida do Sul',
    'Três Arroios',
    'Saldanha Marinho',
    'Fagundes Varela',
    'Dom Pedro de Alcântara',
    'Monte Belo do Sul',
    'Toropi',
    'Mato Castelhano',
    'São Valério do Sul',
    'Herveiras',
    'Faxinalzinho',
    'Dezesseis de Novembro',
    'Quevedos',
    'Barra Funda',
    'Sagrada Família',
    'Maratá',
    'Colinas',
    'São José do Inhacorá',
    'Forquetinha',
    'Cerro Grande',
    'São José das Missões',
    'Santo Expedito do Sul',
    'Nova Pádua',
    'Rolador',
    'São José do Sul',
    'Boa Vista do Incra',
    'Pirapó',
    'Lagoa Bonita do Sul',
    'São Vendelino',
    'Pinhal da Serra',
    'Boa Vista do Cadeado',
    'Coqueiros do Sul',
    'São Valentim do Sul',
    'Poço das Antas',
    'Nova Ramada',
    'Travesseiro',
    'Bozano',
    'Silveira Martins',
    'Novo Tiradentes',
    'Paulo Bento',
    'Porto Mauá',
    'Bom Progresso',
    'Santo Antônio do Palma',
    'Dois Irmãos das Missões',
    'Santo Antônio do Planalto',
    'Benjamin Constant do Sul',
    'Vila Lângaro',
    'Pedras Altas',
    'Nova Boa Vista',
    'Jacuizinho',
    'Protásio Alves',
    'Gramado dos Loureiros',
    'Inhacorá',
    'Vanini',
    'Unistalda',
    'Ubiretama',
    'Almirante Tamandaré do Sul',
    'Sério',
    'Itapuca',
    'Boa Vista das Missões',
    'Nicolau Vergueiro',
    'Ivorá',
    'São José do Herval',
    'Doutor Ricardo',
    'Mariano Moro',
    'Sete de Setembro',
    'Vespasiano Corrêa',
    'Alto Alegre',
    'Relvado',
    'Mato Queimado',
    'São Pedro das Missões',
    'Gentil',
    'Pouso Novo',
    'Lagoa dos Três Cantos',
    'Capão Bonito do Sul',
    'Muliterno',
    'Ipiranga do Sul',
    'Barra do Rio Azul',
    'Linha Nova',
    'Santa Cecília do Sul',
    'Floriano Peixoto',
    'Canudos do Vale',
    'Novo Xingu',
    'Cruzaltense',
    'Coronel Pilar',
    'Vista Alegre do Prata',
    'Ponte Preta',
    'Porto Vera Cruz',
    'Quatro Irmãos',
    'Santa Tereza',
    'Montauri',
    'Guabiju',
    'Tupanci do Sul',
    'Carlos Gomes',
    'Engenho Velho',
    'Coqueiro Baixo',
    'União da Serra',
    'André da Rocha',
  ],
}

const headers = new Headers()
headers.add('Content-Type', 'application/json')

const response = new Response(JSON.stringify(brasil), { headers: headers })
response